---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # https://kubernetes-sigs.github.io/node-feature-discovery/master/deployment/helm.html#chart-parameters
    prometheus:
      enable: true

    worker:
      config:
        core:
          labelSources: ["custom", "pci", "system", "usb"]

        sources:
          pci:
            deviceLabelFields: ["vendor"]
