---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/cilium/app
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: ducknet-ops
  prune: false # should never be deleted
  wait: true
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: gateway-api-experimental-crds
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/cilium/config
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: ducknet-ops
  prune: false # should never be deleted
  wait: true
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: cilium
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-gateway
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/cilium/gateway
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: ducknet-ops
  prune: true
  wait: true
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: cilium
    - name: cilium-config
    - name: cert-manager-issuer-cloudflare
