---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: immich
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.2
  url: oci://ghcr.io/immich-app/immich-charts/immich
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: immich
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: nvidia-device-plugin
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    env:
      DB_HOSTNAME: immich-postgres16-rw.immich.svc.cluster.local
      DB_DATABASE_NAME: immich

      DB_USERNAME: null
      DB_PASSWORD: null

    envFrom:
      - secretRef:
          name: immich-postgres-user-secret

    image:
      tag: v1.125.7

    immich:
      metrics:
        enabled: true

      persistence:
        library:
          existingClaim: immich-library

    redis:
      enabled: true

    machine-learning:
      persistence:
        # Stores ML models
        cache:
          existingClaim: immich-cache

      defaultPodOptions:
        runtimeClassName: nvidia

        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
