---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mc-duckcraft
  namespace: minecraft
spec:
  interval: 30m
  chart:
    spec:
      chart: minecraft
      version: 4.24.0
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml

    resources:
      requests:
        memory: 8Gi

    # StatefulSet to allow server to be stopped
    workloadAsStatefulSet: true
    strategyType: OnDelete

    podLabels:
      containertype: minecraft-server

    extraEnv:
      PAPER_BUILD: 194

    minecraftServer:
      eula: true
      version: 1.21.4
      type: PAPER

      difficulty: hard
      whitelist: duckworld
      ops: duckworld
      maxPlayers: 20
      gameMode: survival
      motd: DuckCraft

      memory: 8192M

      modrinth:
        projects:
          - luckperms:v5.4.145-bukkit
          - tab-was-taken:5.0.7

    serviceAnnotations:
      mc-router.itzg.me/externalServerName: mc.home.ducknet.fun

    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
