---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 70.4.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: prometheus-operator-crds
      namespace: observability
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

    cleanPrometheusOperatorObjectNames: true

    crds:
      enabled: false

    alertmanager:
      route:
        main:
          enabled: true
          hostnames:
            - alertmanager.home.ducknet.fun
          parentRefs:
            - name: internal
              namespace: kube-system
              sectionName: https

      alertmanagerSpec:
        externalUrl: https://alertmanager.home.ducknet.fun

        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 1Gi

    grafana:
      defaultDashboardsTimezone: Australia/Perth

    kubeProxy:
      enabled: false

    prometheus:
      route:
        main:
          enabled: true
          hostnames:
            - prometheus.home.ducknet.fun
          parentRefs:
            - name: internal
              namespace: kube-system
              sectionName: https

      prometheusSpec:
        retention: 14d
        retentionSize: 50GB

        podMonitorSelector:
          matchLabels: null

        probeSelector:
          matchLabels: null

        ruleSelector:
          matchLabels: null

        scrapeConfigSelector:
          matchLabels: null

        serviceMonitorSelector:
          matchLabels: null

        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 50Gi
