---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998

      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-credentials-secret
            namespace: external-secrets

      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt

      organizationID: 20b7071c-700e-4947-9e86-b2bf004d2873
      projectID: 43a24139-886d-451a-b792-b2e70088c170
