---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app threadfin
  namespace: iptv
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      threadfin:
        containers:
          app:
            image:
              repository: docker.io/fyb3roptik/threadfin
              tag: 1.2.31@sha256:78479cea0ec70c72510a98d88b8e34ec3cc695a64cbb92829fd6310d400b2ac6

            env:
              TZ: Australia/Perth

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                memory: 50Mi

    service:
      app:
        controller: threadfin
        ports:
          http:
            port: &port 34400

    route:
      app:
        hostnames:
          - threadfin.home.ducknet.fun
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      config:
        existingClaim: threadfin
        globalMounts:
          - path: /home/threadfin/conf

      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: "RuntimeDefault" }
