---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: descheduler
      version: 0.32.2
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/values.yaml

    kind: Deployment
    replicas: 2

    leaderElection:
      enabled: true

    service:
      enabled: true

    serviceMonitor:
      enabled: true
