---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex
  namespace: plex
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: nvidia-device-plugin
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      plex:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.41.5.9522@sha256:9d612368ec271266f4be4c0aa0daf54dc85ae94959351f020dd3345ca220a303

            env:
              PLEX_ADVERTISE_URL: https://plex.ducknet.fun:443,http://10.4.180.12:32400
              PLEX_NO_AUTH_NETWORKS: 192.168.178.0/23
              TZ: Australia/Perth

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: &port 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 100m
              limits:
                memory: 16Gi
                nvidia.com/gpu: 1

    service:
      app:
        controller: plex
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "10.4.180.12"
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - plex.ducknet.fun
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      config:
        existingClaim: plex
        globalMounts:
          - path: /config

      config-cache:
        existingClaim: plex-cache
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Cache

      config-logs:
        type: emptyDir
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Logs

      transcode:
        type: emptyDir

      anime:
        type: nfs
        server: "10.4.20.10"
        path: /mnt/coeus-pool/media/anime
        globalMounts:
          - path: /media/anime
            readOnly: true

      movies:
        type: nfs
        server: "10.4.20.10"
        path: /mnt/coeus-pool/media/movies
        globalMounts:
          - path: /media/movies
            readOnly: true

      shows:
        type: nfs
        server: "10.4.20.10"
        path: /mnt/coeus-pool/media/shows
        globalMounts:
          - path: /media/shows
            readOnly: true

      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

    defaultPodOptions:
      runtimeClassName: nvidia

      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [4001, 4002, 4004]
        seccompProfile: { type: "RuntimeDefault" }

      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
