---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ducknet-fun
spec:
  secretName: ducknet-fun-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ducknet.fun
  dnsNames:
    - ducknet.fun
    - "*.ducknet.fun"
    - "*.home.ducknet.fun"
