---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg17
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4-6-bullseye

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-secret

  instances: 1

  monitoring:
    enablePodMonitor: true

  storage:
    size: 5Gi
    storageClass: openebs-hostpath
