---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager

  target:
    name: authentik-postgres-secret

    template:
      engineVersion: v2
      data:
        username: "{{ .AUTHENTIK_POSTGRES_USER }}"
        password: "{{ .AUTHENTIK_POSTGRES_PASS }}"

  dataFrom:
    - extract:
        key: 2e42595b-7c0f-443f-92bf-b2a700931b9e
