---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik
spec:
  schedule: "0 0 */6 * * *" # Every 6 hours
  immediate: true
  backupOwnerReference: self
  cluster:
    name: authentik-pg17
