---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fstrim
  namespace: fstrim
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        type: cronjob

        cronjob:
          schedule: "@daily"
          parallelism: 1 # Number of nodes
          successfulJobsHistory: 1
          failedJobsHistory: 1

        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/alpine
              tag: 3.21.3

            command: ["/bin/sh", "-c"]
            args:
              - |
                nsenter --mount=/host/proc/$(pidof /usr/local/bin/kubelet)/ns/mnt --net=/host/proc/$(pidof /usr/local/bin/kubelet)/ns/net -- sh -c "fstrim --verbose --quiet-unsupported --all"

            resources:
              requests:
                cpu: 25m
              limits:
                memory: 128Mi

            securityContext:
              privileged: true

    persistence:
      procfs:
        type: hostPath
        hostPath: /proc
        hostPathType: Directory
        globalMounts:
          - path: /host/proc
            readOnly: true

      netfs:
        type: hostPath
        hostPath: /sys
        hostPathType: Directory
        globalMounts:
          - path: /host/net
            readOnly: true

    defaultPodOptions:
      hostNetwork: true
      hostPID: true
