---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-router
  namespace: minecraft
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: itzg-mc-router
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # https://github.com/itzg/minecraft-server-charts/blob/master/charts/mc-router/values.yaml

    minecraftRouter:
      autoScaleUp:
        enabled: true

      connectionRateLimit: 2

    services:
      minecraft:
        type: LoadBalancer
        annotations:
          "io.cilium/lb-ipam-ips": "10.4.180.11"
