---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-router
  namespace: minecraft
spec:
  interval: 30m
  chart:
    spec:
      chart: mc-router
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # https://github.com/itzg/minecraft-server-charts/blob/master/charts/mc-router/values.yaml

    minecraftRouter:
      connectionRateLimit: 2

    services:
      minecraft:
        type: LoadBalancer
        annotations:
          "io.cilium/lb-ipam-ips": "10.4.180.11"
