---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager

  target:
    name: operator-oauth

    template:
      engineVersion: v2
      data:
        client_id: "{{ .clientId }}"
        client_secret: "{{ .secret }}"

  dataFrom:
    - extract:
        key: bbb7b676-6e5e-41c7-9f8b-b26300a0d8a5
