---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: duckcraft
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft
  interval: 1h
  values:
    image:
      repository: itzg/minecraft-server
      tag: 2026.8.1-java25@sha256:1bfb278ea9ee9a319ff2b6ebf6e996e7217fbcd825a925f6382d05bd348c046b

    minecraftServer:
      eula: "TRUE"
      version: "26.2"
      type: FABRIC

      difficulty: hard
      ops: duckworld
      maxPlayers: 20
      gameMode: survival
      motd: DuckCraft

      memory: 8192M

      modrinth:
        projects:
          # Core
          - fabric-api:0.154.0+26.2
          - proxy-protocol-support:1.2.1-fabric

          # Optimisation
          - ferrite-core:9.0.0-fabric

          # o11y
          - fabricexporter:1.0.22
          - spark:1.10.173-fabric

      extraEnv:
        PREFER_IPv6: "true"

      extraPorts:
        - name: metrics
          containerPort: 25585
          protocol: TCP
          service:
            enabled: true
            port: 9100

    serviceAnnotations:
      mc-router.itzg.me/externalServerName: duckcraft.mc.${DOMAIN_DN}

    resources:
      requests:
        cpu: 2000m
        memory: 8192Mi

    persistence:
      dataDir:
        enabled: true
        existingClaim: duckcraft

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      fsGroupChangePolicy: OnRootMismatch
