---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.16.6
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  values:
    # https://rook.io/docs/rook/latest-release/Helm-Charts/ceph-cluster-chart/#configuration

    monitoring:
      enabled: true
      createPrometheusRules: true

    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard = true
      osd_class_update_on_start = false
      osd_pool_default_size = 1
      mon_warn_on_pool_no_redundancy = false

    cephClusterSpec:
      mon:
        count: 1
        allowMultiplePerNode: false

      mgr:
        count: 1
        allowMultiplePerNode: false

        modules:
          - name: insights
            enabled: true
          - name: pg_autoscaler
            enabled: true
          - name: rook
            enabled: true

      dashboard:
        enabled: true
        ssl: false
        prometheusEndpoint: http://prometheus-operated.observability.svc.cluster.local:9090

      storage:
        useAllNodes: false
        useAllDevices: false

        config:
          encryptedDevice: "true"
          osdsPerDevice: "1"

        nodes:
          - name: talos-prox
            devices:
              - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1

    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 1
            requireSafeReplicaSize: false

        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          mountOptions: ["discard"]

          parameters:
            # RBD image format
            imageFormat: "2"

            # RBD image features. Linux kernel 5.4+ supports all features
            imageFeatures: layering,exclusive-lock,object-map,fast-diff,deep-flatten

            # Secrets automatically created by Rook
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"

            # Volume filesystem
            csi.storage.k8s.io/fstype: ext4

    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: ceph-block
      isDefault: false
      deletionPolicy: Delete

    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 1
              requireSafeReplicaSize: false

          dataPools:
            - failureDomain: host
              replicated:
                size: 1
                requireSafeReplicaSize: false
              name: &pool data0

          preserveFilesystemOnDelete: true

          metadataServer:
            activeCount: 1
            activeStandby: true

        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          pool: *pool
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: "Immediate"

          parameters:
            # The secrets contain Ceph admin credentials.
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/fstype: ext4

    cephFileSystemVolumeSnapshotClass:
      enabled: true
      name: ceph-filesystem
      isDefault: true
      deletionPolicy: Delete

    cephObjectStores: []
