---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mc-router
  namespace: flux-system
spec:
  path: ./kubernetes/apps/minecraft/router
  targetNamespace: minecraft
  sourceRef:
    kind: GitRepository
    name: ducknet-ops
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mc-duckcraft
  namespace: flux-system
spec:
  path: ./kubernetes/apps/minecraft/duckcraft
  targetNamespace: minecraft
  sourceRef:
    kind: GitRepository
    name: ducknet-ops
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: mc-router
    - name: volsync
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mc-smp-spring-to-life
  namespace: flux-system
spec:
  path: ./kubernetes/apps/minecraft/smp-spring-to-life
  targetNamespace: minecraft
  sourceRef:
    kind: GitRepository
    name: ducknet-ops
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: mc-router
    - name: volsync
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 50Gi
