---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
spec:
  chartRef:
    kind: OCIRepository
    name: kopiur
  interval: 1h
  values:
    image:
      controller:
        repository: jackmyers001/kopiur-controller
        digest: sha256:dcadfb597756bf4d60533561b6a83bee035981dcead8c7146bfe52d877aef9d3

    controller:
      extraEnv:
        - name: KOPIUR_CONTROLLER_ADDR
          value: "[::]:8081"
      extraVolumes:
        - name: repo
          nfs:
            server: coeus.storage.internal
            path: /mnt/coeus-pool/k8s/kopiur
      extraVolumeMounts:
        - name: repo
          mountPath: /repo

      resources:
        requests:
          cpu: 100m
        limits:
          memory: 2Gi

      streamingLists: true

    features:
      credentialProjection:
        enabled: true

    grafanaDashboard:
      enabled: true
      grafanaOperator:
        enabled: true
        matchLabels:
          dashboards: grafana

    installScope: cluster

    metrics:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      fsGroupChangePolicy: OnRootMismatch

    webhook:
      listenAddr: "[::]:8443"
      tls:
        mode: self
      serviceMonitor:
        enabled: true
