---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager

  target:
    name: sonarr-secret

    template:
      data:
        SONARR__AUTH__APIKEY: "{{ .SONARR_API_KEY }}"

  dataFrom:
    - extract:
        key: ff545276-d258-4aae-a1de-b2f100cf1bda
