---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager

  target:
    name: authentik-secret

    template:
      engineVersion: v2
      data:
        secretKey: "{{ .AUTHENTIK_SECRET_KEY }}"

  dataFrom:
    - extract:
        key: 2e42595b-7c0f-443f-92bf-b2a700931b9e
