---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chartRef:
    kind: OCIRepository
    name: plex
  interval: 1h
  values:
    controllers:
      plex:
        containers:
          app:
            image:
              repository: ghcr.io/jackmyers001/plex
              tag: 1.43.3.10793-cd55560bb@sha256:05c19f3fd193d938ffa4905d9a7e7964515728f1cb2b5eedf0124ff5f5da2f32

            env:
              PLEX_ADVERTISE_URL: https://plex.${DOMAIN_DN}:443,http://10.4.180.21:32400
              TZ: Australia/Perth

            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5

              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: &port 32400
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5

              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 100m
              limits:
                memory: 16Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [4001, 4002, 4004]

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${DOMAIN_DN}"
        parentRefs:
          - name: envoy-external
            namespace: envoy-gateway-system
          - name: envoy-internal
            namespace: envoy-gateway-system
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"

      media:
        type: nfs
        server: coeus.storage.internal
        path: /mnt/coeus-pool/media
        globalMounts:
          - path: /media
            readOnly: true

      tmp:
        type: emptyDir
