---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager

  target:
    name: recyclarr-secret

    template:
      engineVersion: v2
      data:
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"

  dataFrom:
    - extract:
        key: 60c43d0d-7e6e-44a5-81ea-b27400e038de
    - extract:
        key: 768b13ea-c15e-4b4d-a7c8-b27e00c884b7
