---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-r2-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager

  target:
    name: cnpg-r2-backup-secret

    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .accessKey }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretKey }}"

  dataFrom:
    - extract:
        key: a5247260-3873-49c7-b959-b27300d650fc
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager

  target:
    name: cnpg-superuser-secret

    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"

  dataFrom:
    - extract:
        key: b8e78d3f-e8b8-40e8-b667-b274007d57a2
