---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./servicemonitor.yaml
  - ../../../template/volsync
configMapGenerator:
  - name: fabric-mod-config-configmap
    files:
      - antixray.toml=./resources/config/antixray.toml
      - sessility.properties=./resources/config/sessility.properties
generatorOptions:
  disableNameSuffixHash: true
