---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: recyclarr
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./recyclarr/ks.yaml
