---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgres-user
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager

  target:
    name: immich-postgres-user-secret

    template:
      engineVersion: v2
      data:
        username: "{{ .IMMICH_POSTGRES_USER }}"
        password: "{{ .IMMICH_POSTGRES_PASS }}"

        DB_USERNAME: "{{ .IMMICH_POSTGRES_USER }}"
        DB_PASSWORD: "{{ .IMMICH_POSTGRES_PASS }}"

  dataFrom:
    - extract:
        key: 11dc9789-5e87-43b4-b01d-b27700864c2e
