---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-crds
  namespace: flux-system
spec:
  path: ./client/config/crd
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  prune: false # should never be deleted
  wait: true
  interval: 30m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-snapshot-controller
  namespace: flux-system
spec:
  path: ./deploy/kubernetes/snapshot-controller
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  prune: false # should never be deleted
  wait: true
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: external-snapshotter-crds
