---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  path: ./kubernetes/apps/cnpg-system/app
  targetNamespace: cnpg-system
  sourceRef:
    kind: GitRepository
    name: ducknet-ops
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: openebs
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-cluster
  namespace: flux-system
spec:
  path: ./kubernetes/apps/cnpg-system/cluster
  targetNamespace: cnpg-system
  sourceRef:
    kind: GitRepository
    name: ducknet-ops
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: cnpg
