---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/metrics-server/app
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: ducknet-ops
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
