---
instance:
  distribution:
    version: 2.5.1

  cluster:
    networkPolicy: false

  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller

  sync:
    kind: GitRepository
    url: https://github.com/JackMyers001/ducknet-ops
    ref: refs/heads/main
    path: kubernetes/apps
    interval: 1h

  commonMetadata:
    labels:
      app.kubernetes.io/name: flux

  kustomize:
    patches:
      - # Cluster sync SOPS decryption
        patch: |
          - op: add
            path: /spec/decryption
            value:
              provider: sops
              secretRef:
                name: sops-age
        target:
          group: kustomize.toolkit.fluxcd.io
          kind: Kustomization

      - # Add SOPS decryption to child Kustomizations
        patch: |
          - op: add
            path: /spec/patches
            value: []
          - op: add
            path: /spec/patches/-
            value:
              patch: |-
                apiVersion: kustomize.toolkit.fluxcd.io/v1
                kind: Kustomization
                metadata:
                  name: not-used
                spec:
                  decryption:
                    provider: sops
                    secretRef:
                      name: sops-age
              target:
                kind: Kustomization
                group: kustomize.toolkit.fluxcd.io
        target:
          group: kustomize.toolkit.fluxcd.io
          kind: Kustomization

      - # Increase concurrency
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=10
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --requeue-dependency=5s
        target:
          kind: Deployment
          name: (kustomize-controller|helm-controller|source-controller)
