apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  DOMAIN_DN: ENC[AES256_GCM,data:FigimHi1PUss1ds=,iv:xl1cFo9VXZYvw92D7JkrDOEc0dhkWL/GOx+vO4hwZt4=,tag:8hmGusM6X4WpgkNxqQoqpw==,type:str]
  DOMAIN_JM: ENC[AES256_GCM,data:gMp8sRjuh9ZfMR9ztg==,iv:ZcWrnrUjaGtu6Fxj86CR24LUcshVZcKCEbEFNF7gWjU=,tag:qaphCM3xao8N/ZxU6xsp6A==,type:str]
sops:
  age:
    - recipient: age1lvw3vk45jdtlvd69shth867ex5zqwghm85muq8aexux85nuf6vnqd5csxr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVEtJL05URmNrQUY1Zis5
        RnFUcWlYOU9xNVp0eTNzS1g4cW5BYm5nRlVzCmlzMnE3UlRUa0xGNzJCQ2xGcDJj
        cW4yUFI3aWZmbEk5MFZaVlYwNjNtUFUKLS0tIGdHWWZiVTc5dzZVYzErb1YzRERR
        UmxTaVBkYjcyNWN3b3kxbklYQUVOckkK+SKgHZ5ibX9ryuVmwo7eLZpRznOs+8mh
        aoIkkBO1Lh4Lt7sB7SIWfMgMw6/3B6fH4H9gewX9Z8AQFp/FGkmlGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-29T15:07:51Z"
  mac: ENC[AES256_GCM,data:AwSyTMFNCzR+w1TtFJT6R2dCQwE3IKtYVMxLcCwUjibLh0TAHkce7f3O/H64pAyd8/6sGaTSGqC5Yhoq5n9ocuGPBG/w48eqBCstxdm4MJ9a2KYANeeOxm+U/zBEJXRVQhAKOgjxPFIsdKz2hBGkwxobs7ZQ08Lr7I9AO6uPfdQ=,iv:dVfFbQcPKmm/fhWQUlyjWYH8QC+geoYtwFvCapgumu4=,tag:DsdD1RHeNWoFJh76kdWQcg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
