---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr
  namespace: flux-system
spec:
  path: ./kubernetes/apps/radarr/app
  targetNamespace: radarr
  sourceRef:
    kind: GitRepository
    name: ducknet-ops
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: external-secrets-stores
    - name: volsync
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
