---
apiVersion: v1
kind: Namespace
metadata:
  name: sonarr
  labels:
    pod-security.kubernetes.io/enforce: &ps baseline # Required for NFS volumes
    pod-security.kubernetes.io/audit: *ps
    pod-security.kubernetes.io/warn: *ps
