---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # https://github.com/openebs/openebs/blob/main/charts/values.yaml

    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false

      replicated:
        mayastor:
          enabled: false

    # Don't install external-snapshotter CRDs
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
