---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: global-secrets
spec:
  externalSecretName: global-secrets

  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: bitwarden-secrets-manager

    target:
      name: global-secrets
      template:
        data:
          DOMAIN_DN: "{{ .DOMAIN_DN }}"
          IPV6_BASE: "{{ .IPV6_BASE }}"

    dataFrom:
      - extract:
          key: 3a4d5795-189c-46ff-9f03-b46200f7f8a3

  namespaceSelector:
    matchExpressions: []
