---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager

  target:
    name: coder-secret

    template:
      engineVersion: v2
      data:
        CODER_EXTERNAL_AUTH_0_CLIENT_ID: "{{ .CODER_GITHUB_CLIENT_ID }}"
        CODER_EXTERNAL_AUTH_0_CLIENT_SECRET: "{{ .CODER_GITHUB_CLIENT_SECRET }}"
        CODER_PG_CONNECTION_URL: postgres://{{ .CODER_POSTGRES_USER }}:{{ .CODER_POSTGRES_PASSWORD }}@postgres17-rw.cnpg-system.svc.cluster.local:5432/coder?sslmode=disable

        INIT_POSTGRES_DBNAME: coder
        INIT_POSTGRES_HOST: postgres17-rw.cnpg-system.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .CODER_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .CODER_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: b8e78d3f-e8b8-40e8-b667-b274007d57a2
    - extract:
        key: 6d20ffcc-e0f0-4279-8474-b28500803943
