---
name: Quality - hk Checks

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  hk:
    name: hk Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@94c60b39bc2d90ab2f9bab27f38d3cc4812c1834 # v5.1.0

      - name: Run hk
        shell: bash
        run: hk check --all
