---
name: Quality - Flate Test

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/quality-flate-test.yaml
      - kubernetes/**

permissions: {}

jobs:
  test:
    name: Flate Test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Flate
        uses: home-operations/flate/action@af6f188c520a6a9c55b4b863bb9c77227e5fd37f # v0.5.1
        with:
          cache: true

      - name: Run Flate test
        env:
          FLATE_PATH: kubernetes/flux/cluster
        run: flate test all --allow-missing-secrets
