---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager

  target:
    name: recyclarr-secret

    template:
      data:
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"

  dataFrom:
    - extract:
        key: 41aa4e16-cbc1-4112-86eb-b2e7008ad013
    - extract:
        key: ff545276-d258-4aae-a1de-b2f100cf1bda
