[tools]
"aqua:nushell/nushell" = "latest"
bitwarden = "latest"
bitwarden-secrets-manager = "latest"
"cargo:https://github.com/nushell/nufmt" = "latest"
helm = "latest"
hk = "latest"
kubectl = "latest"
kustomize = "5.8.1"
oxfmt = "latest"
pkl = "latest"
vals = "latest"

[tasks.lint]
run = "hk check --all --slow"

[tasks.lint-fix]
run = "hk fix --all --slow"
