---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_DN/./-}"
spec:
  secretName: "${DOMAIN_DN/./-}-tls"

  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

  commonName: "${DOMAIN_DN}"

  dnsNames:
    - ${DOMAIN_DN}
    - "*.${DOMAIN_DN}"
    - "*.home.${DOMAIN_DN}"
